version: '3.8'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=recipenote
      - DB_USERNAME=root
      - DB_PASSWORD=root

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    user: 1001:1001
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: recipenote
      MYSQL_USER: recipenote
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./redis/redis.conf:/etc/redis.conf"